### ISSUE TITLE
can this compiler  compile linux kernel?

### ISSUE THREAD

**Issue by gggin** [kawakami-o3/rcc#11]

**Comment by kawakami-o3** [comment]
Unfortunately, no, not yet.
To compile linux kernel, r9ir needs some compatibility with gcc.
And r9ir supports just a subset of C, so it don't have enough features.

Your question is very interesting for me.
The goal of r9ir was full compatibility with rui314/9cc https://github.com/rui314/9cc .
I will try compiling linux kernel as the next goal.
Thank you for your great suggestion.

**Comment by gggin** [comment]
ok, just a suggestion. If you have time to response me a lot of words. (tks). You can write a current stage or feature list for people to learn and study.
